### ISSUE TITLE
Politically incorrect region name "Taiwan, Province of China"

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [AfterShip/phone#100]
(This issue is forwarded from [Politically incorrect region name "Taiwan, Province of China" · Issue #626 · GitbookIO/feedback](https://github.com/GitbookIO/feedback/issues/626))

The region name "Taiwan, Province of China" is politically incorrect and offending to Taiwanese users, please use the neutral name "Taiwan" instead.

If the application relies on the iso-codes package, please use the "common name" field when available instead as with this [patch](https://launchpadlibrarian.net/53161408/use_common_name_instead_when_it_exists.patch) did with the [Ubuntu LoCo Team Portal](http://loco.ubuntu.com/) site.

REF: 

* [Bug #614236 “Wrong Country Name. (Taiwan)” : Bugs : LoCo Team Portal](https://bugs.launchpad.net/loco-team-portal/+bug/614236)
* [Politically incorrect region name "Taiwan, Province of China" · Issue #310 · canonical-websites/snapcraft.io](https://github.com/canonical-websites/snapcraft.io/issues/310)

Thanks in advance!

**Comment by hans-lizihan** [comment]
fixed in this PR #104
