### ISSUE TITLE
566 area code not valid

### ISSUE THREAD

**Issue by anaptfox** [AfterShip/phone#133]
Re: https://github.com/AfterShip/phone/issues/1

It looks like 566 is a valid area code, but it's non-geographic. 

See: https://nationalnanpa.com/pdf/PL_436.pdf

**Comment by Bossa573** [comment]
Can you provide more information about US phone number with prefix `566`? And what does `non-geographic` mean?

**Comment by anaptfox** [comment]
I'm not 100% sure. It was a requirement from a customer of ours. But, according to them and the document I linked above, it seems to be a valid phone number.

**Comment by Bossa573** [comment]
@anaptfox I have looked up some of the websites the search for the area code `566` but no luck:

https://countrycode.org/usa
https://www.allareacodes.com/area_code_listings_by_state.htm
https://www.50states.com/areacodes/

and on this website:
https://www.areacodelocations.info/areacodelist.html

It stated that `566` is for "Personal Communications Services":
![image](https://user-images.githubusercontent.com/1013526/53718772-239d3580-3e97-11e9-9931-8bb225b14ba8.png)

I am unable to confirm if `566` is a valid area code by only the provided PDF

**Comment by Bossa573** [comment]
please reopen the ticket if more information found, thanks
