### ISSUE TITLE
ukrainian mobile phone numbers

### ISSUE THREAD

**Issue by Bossa573** [AfterShip/phone#142]
from https://github.com/AfterShip/phone/pull/119 and https://github.com/AfterShip/phone/pull/98

Here is the table combining both source:

code prefix | wiki | maanimo.com | Current phone module support?
-- | -- | -- | --
39 | | | ✓
50 | Vodafone | Vodafone | ✓
63 | lifecell | lifecell | ✓
66 | Vodafone | Vodafone | ✓
67 | Kyivstar | Kyivstar | ✓
68 | Kyivstar |  | ✓
73 | lifecell | lifecell | ✓
891 | Datagroup
892 | Ukrtelecom
893 | Global
894 | O3 / mixnet
895 | Link-3000
896 | Vodafone
897 | Kyivstar
899 | Velton.Telecom
91 | ThreeMob | ThreeMob / PeopleNet / Intertelecom | ✓
92 | PeopleNet | ThreeMob / PeopleNet / Intertelecom | ✓
93 | lifecell | lifecell | ✓
94 | Intertelecom | ThreeMob / PeopleNet / Intertelecom | ✓
95 | Vodafone | Vodafone | ✓
96 | Kyivstar | Kyivstar | ✓
97 | Kyivstar | Kyivstar | ✓
98 | Kyivstar | Kyivstar | ✓
99 | Vodafone | Vodafone | ✓

# 68
Only exists on wiki, unable to verify the correctness

# 89x
Only exists on wiki, unable to verify the correctness

# 91, 92, 94
From https://maanimo.com/helpful/142623-kody-operatorov

```
(translated)
91 - belongs to the operator Trimob from the company Ukrtelecom and sent to use high-quality 3G-Internet;

92 - is PeopleNet, which is also used mainly for the Internet;

94 - owned by Intertelecom, which has long been trying to create competition to the three main Ukrainian operators, but so far unsuccessfully. 94 is new and almost unknown at the moment;
```

`91` is seems to be valid, but `92` and `94` is doubtful

@DanielMazurkiewicz @Kamikadze4GAME please help to review and resolving `68`, `89x`, `91`, `92`, `94` before I merge the codes, thanks

**Comment by DanielMazurkiewicz** [comment]
@Bossa573 - can't tell you more than you know already, except that AFAIK 91 and 92 is used for both - data and voice services. About 89x I can tell you that I have customers in my db with such an mobile number that is able to receive SMS message at least.

**Comment by Bossa573** [comment]
This is the current value in `iso3166Data.js` :

```javascript
mobile_begin_with: ['39', '50', '63', '66', '67', '68', '73', '9'],
```

Supposedly it should have already covered all the mobile prefix provided by `maanimo.com`, and even include `68` from the wikipedia, except:

1. the module includes `39`, which none of the source specify such prefix
2. the module didn't include any `89x` prefix

@DanielMazurkiewicz  @Kamikadze4GAME see if you need to fix (1) and (2), or the current version should be good enough for Ukraine, thanks

**Comment by Bossa573** [comment]
@DanielMazurkiewicz @Kamikadze4GAME closing the issue,
please reopen if you find the current data set cannot fulfill the needs (can check the tables above)
