### ISSUE TITLE
Netherlands phone number returning empty array

### ISSUE THREAD

**Issue by Liel208** [AfterShip/phone#145]
Validation for NL phone:+31623638101‬ without country code returning an empty array, although it is a valid NL phone.

Phone('+31623638101‬', 'NL') => return ['+31623638101', 'NLD'] // this works
Phone('+31623638101‬') => returns [] // expected to be the same as above

**Comment by Bossa573** [comment]
I'm unable to replicate your issue:

```javascript
const phone = require('phone');
const result = phone('+31623638101');
console.log(result);
```
```
➜  testphone node index.js
[ '+31623638101', 'NLD' ]
```

and I noticed that there are some hidden character when I copy the text from the issue:
![image](https://user-images.githubusercontent.com/1013526/58311643-034c9980-7e3c-11e9-9937-21cf6980cc33.png)
You might want to see if it's related

**Comment by Bossa573** [comment]
Please provide more information and reopen the issue if needed
