### ISSUE TITLE
US 800 #s

### ISSUE THREAD

**Issue by ekkis** [AfterShip/phone#147]
I have the same problem as https://github.com/AfterShip/phone/issues/146 but I'm using '+1 (800) 555 1212', which is standard for testing.  I get an empty array.  this should be acceptable and should format properly

**Comment by ekkis** [comment]
the problem is that the `mobile_begin_with` field in `iso3166Data.js` for the US does not contain the 800 area code.  Curiously, it does contain the 888, which is also a toll-free area code.  so it's inconsistent that way.  it should include 800

if I provide a PR will you merge?

**Comment by ekkis** [comment]
in any case, in the US there are no special area codes for mobile numbers

**Comment by Bossa573** [comment]
Hi @ekkis,
all PRs are welcome for sure.
for such case, please attach any references (websites, wiki, PDFs, etc) for the related change

**Comment by ekkis** [comment]
awesome.  it may take me a few days.  super busy right now.  not sure what you mean about references

**Comment by Bossa573** [comment]
@ekkis it's refering to any material that showing `800` is the US's area code

**Comment by ekkis** [comment]
you mean that 800 is an area code within the US? it is because I use it all the time.  I'm not sure there's "material" on the subject but it's easily verified

**Comment by Bossa573** [comment]
@ekkis 
I see.

Because we are unable to verify every area codes in every country, 
we have to rely on all the material we could find.
(We are not US-based either)

Anyway I found a supporting article showing the usage of `800`
https://en.wikipedia.org/wiki/Wide_Area_Telephone_Service
but I'm unable to tell if it is an area code used by *mobile phone number*

**Comment by ekkis** [comment]
within the NANP zone (which includes Canada, the US and a number of other countries), 800 and 888 are treated as toll-free numbers but there is no specification that they cannot be hosted by a cell phone.  in fact, they can, because NANP makes no special distinction for mobile handsets.  see: https://en.wikipedia.org/wiki/List_of_North_American_Numbering_Plan_area_codes

**Comment by Bossa573** [comment]
For this case, I'll add `800` to the list, 
please check the new release `2.3.13`.

https://github.com/AfterShip/phone/releases/tag/2.3.13

**Comment by ekkis** [comment]
awesome, and thank you!

**Comment by dalepo** [comment]
is this working? currently using 2.3.18 and (800) is not passing validation.
Thanks!

**Comment by Bossa573** [comment]
@dalepo Please provide full phone number and the code snippet, and even better, create a new separated issue
