### ISSUE TITLE
Error with source-map while building

### ISSUE THREAD

**Issue by ebaynaud** [AfterShip/phone#151]
AfterShip/phone is a dependency of my project and I recently meet some build issues due to source-map, probably due to: https://github.com/webpack-contrib/babel-minify-webpack-plugin/issues/68

I will PR in a few minute a workaround to disable source-map.

Issue details:
```
93% after chunk asset optimization SourceMapDevToolPlugin index.js generate SourceMap/myprojectpath/node_modules/phone/node_modules/babel-minify-webpack-plugin/node_modules/source-map/lib/source-map-generator.js:276
        throw new Error(
        ^

Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
```

**Comment by Bossa573** [comment]
Please provide the code snippet which illustrates the issue,
we haven't seen any similar case with webpack.

**Comment by Bossa573** [comment]
temporarily disable the source map to prevent blocking the workflow,
need to investigate https://github.com/webpack-contrib/babel-minify-webpack-plugin/issues/68 and https://github.com/mozilla/source-map/issues/385

**Comment by Bossa573** [comment]
meanwhile please check https://github.com/AfterShip/phone/releases/tag/2.3.16

**Comment by Bossa573** [comment]
babel-minify-webpack-plugin has already been archived and expects no more update on this.
closing this issue and pending for the improvement on the future version
