### ISSUE TITLE
New numbers in Nigeria

### ISSUE THREAD

**Issue by xream** [AfterShip/phone#161]
https://en.wikipedia.org/wiki/Telephone_numbers_in_Nigeria

https://github.com/AfterShip/phone/blob/6643141a09a18b252c557c017bb6a8bc305b9a8e/lib/iso3166Data.js#L1250

I think it should be `['70', '80', '81', '90']`.

**Comment by Bossa573** [comment]
@xream thanks for the comment,
yes I think `90` should be included
Can you create a PR for this?
