### ISSUE TITLE
How to force response using ISO-3661 2-char country code (instead of 3-char)?

### ISSUE THREAD

**Issue by tfrancois** [AfterShip/phone#162]
Is there a way to force response to use 2-character country code rather than the current default of the 3-digit country code?  More systems use the ISO-3661 Alpha-Code 2 than the alternative.  Please advise.  And thank you for this great and compact library!

**Comment by Bossa573** [comment]
@tfrancois 
https://github.com/michaelwittig/node-i18n-iso-countries#readme
you can use this package to convert from alpha 3 to alpha 2 and vice versa (and much more features)
we also use this package a lot.

Thanks for using `phone` lib 👍
