### ISSUE TITLE
Error validating phone number +5599988311895 as 'BRA' (brazilian)

### ISSUE THREAD

**Issue by joaobrunoah** [AfterShip/phone#169]
This is a valid phone number but is not being recognized as such.

I'm using the function as follows:

    // corrected_phone_number = undefined
    const [corrected_phone_number,country] = phone('+5599988311895','BRA');

**Comment by Bossa573** [comment]
according to 
https://en.wikipedia.org/wiki/List_of_dialling_codes_in_Brazil#Maranh%C3%A3o_(98_and_99)
should include `99` for the area code
willl create PR for this

**Comment by Bossa573** [comment]
https://github.com/AfterShip/phone/releases/tag/2.4.2
