### ISSUE TITLE
Are alpha 2 ISO country codes allowed in the API?

### ISSUE THREAD

**Issue by filetvignon** [AfterShip/phone#171]
Found no mention of it in the docs but it appears to be accepted.
e.g. `phone('(11) 97857-8900', 'BR')` works the same as `phone('(11) 97857-8900', 'BRA')`

**Comment by Bossa573** [comment]
You are right, according to the code:
https://github.com/AfterShip/phone/blob/master/lib/getISO3166.js#L13
the library should be able to accept iso 3166-2 country code which is 2 characters only.
Thanks for the heads up and I will update the documentation soon.
