### ISSUE TITLE
version 2.4.6 brokes all vue object as JSON rendering in templates

### ISSUE THREAD

**Issue by yariksav** [AfterShip/phone#180]
Hi!
The new version 2.4.6 brokes all vue object as JSON rendering in templates.

After adding babel-polifyl it overrided Object.prototype.toString global function

This is how Vue renders objects in template
![image](https://user-images.githubusercontent.com/2553313/74602463-5e50ab80-50b1-11ea-9cf8-e217a89f0160.png)

now val.toString and _toString is different functions

Then when you add to any vue template {{ { test: 'foo' } }} it will render now [object: Object] instead { test: 'foo' }

rollback to version 2.4.4

**Comment by Bossa573** [comment]
Hello,
While I'm not familiar with Vue.js,
I'm unable to find any documents or discussions about compatibility issues between vue.js and babel-polyfill / idempotent-babel-polyfill.
Can you find some documents states the incompatibilities?

**Comment by yariksav** [comment]
I suppose all polifyl's must setup directly in projects, not in npm modules

Can you make two versions one with babel-polyfill  and second without? Because most of projects use webpack compilation and doesn't require polifyl's (or setup it by itself), and now it's excess code.

in package.json you can setup which file is respond for which module: for main or for browser

**Comment by Bossa573** [comment]
We're going to revert the polyfill module and use an alternate method to achieve the same result, the new version will be released within this few days

**Comment by Bossa573** [comment]
released 2.4.7 which removed babel-polyfill, can you test again?

**Comment by Bossa573** [comment]
closing ticket, please reopen if needed

**Comment by yariksav** [comment]
Thank you. Everything works fine!
