### ISSUE TITLE
Minified release causes side effect for Date and JSON.stringify

### ISSUE THREAD

**Issue by vdh** [AfterShip/phone#182]
Due to some very hard-to-debug weirdness (since `phone/dist/index.js` is minified), something in the minification process used for release (perhaps `core-js`), is making modifications to the `Date` prototype that causes issues in completely unrelated code (in my case, Storybook's addon-actions and stringifying an event object).

I've narrowed it down to definitely the `node_modules/phone/dist/index.js` file because swapping it out for a mock or the raw source from `phone/lib` doesn't trigger the error.

Since `phone` doesn't use `Date`, you might want to change your `core-js` / minification settings to exclude unused polyfills. Additionally, you could include `lib` in the release as an option to skip the minified version entirely.

**Comment by Bossa573** [comment]
Hello,
did you check the latest version `2.4.7` which removed babel-polyfill completely?

**Comment by vdh** [comment]
@Bossa573 Not yet, I'll give that version a check

**Comment by vdh** [comment]
@Bossa573 Yep, that version solves the issue 👍
