### ISSUE TITLE
Input with just + character in front of number returns input without country code

### ISSUE THREAD

**Issue by finnmich** [AfterShip/phone#190]
Example:
phone("+41414141","NO") returns ["+41414141", "NOR"].

It should return ["+4741414141", "NOR"] (Or maybe empty array?)

(For information NO mobile numbers are 8 digists and always start with 4 or 9)

Found the same issue for Swedish numbers.

**Comment by Bossa573** [comment]
Hello, 
Thanks for the report, and this is fixed in 2.4.10 which is just released.
