### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by eveningkid** [AfterShip/phone#196]
Hey,

I did not know how to reach out otherwise.

I just wanted to thank you for your work! It might sound silly but we all need this kind of packages and these days, we take this for granted as we can find such projects within seconds :)

But behind this I know there's work, and I needed to thank you for that!

Keep it up

**Comment by Bossa573** [comment]
Hi there, 

Thank you for your comment and support on this package,
and we will keep improving and aim for a lot more improvements in the future major version updates,
including types, better API interface, proper landline supports and more.

Thank you for using our package.
