### ISSUE TITLE
Kenyan Phone Numbers

### ISSUE THREAD

**Issue by ALWISHARIFF** [AfterShip/phone#197]
Hello,
Kenyan Operators Have released a new set of phone Numbers starting with countryCode:(254),NewNumber:( 1 )+2541 A minor change to be done.
Thank you

**Comment by Bossa573** [comment]
Thanks for the reports, is there any documentation or website showing this change for references?

**Comment by ALWISHARIFF** [comment]
Hello,
https://www.dignited.com/57218/safaricom-introduces-new-prefix-numbers-0110-and-0111/
https://www.tuko.co.ke/318865-safaricom-prefixes-phone-numbers.html
To verify more you can call me +254111437457
Thank you

**Comment by Bossa573** [comment]
thanks and included in https://github.com/AfterShip/phone/releases/tag/2.4.13

**Comment by ALWISHARIFF** [comment]
https://reversephonenumberlookup.pro/
