### ISSUE TITLE
Canadian phone numbers, can't recognise country

### ISSUE THREAD

**Issue by atrofimenko** [AfterShip/phone#198]
Hello!
I found a problem with a canadian numbers, like 12045552348 - it can't be found using this lib.

**Comment by atrofimenko** [comment]
import phoneLib from 'phone';

const phoneNumber = '12045552348';
phoneLib(phoneNumber);

//result is [] - empty array

**Comment by Bossa573** [comment]
I re-verified the logic, 
as if there is no plus sign before the phone number, and no country provided,
the logic will simply assume the country is USA.

To improve the detecting accuracy, please add a '+' sign before the phone number (if you're sure that the phone number always come with country code):

```
import phoneLib from 'phone';

const phoneNumber = '+12045552348';
phoneLib(phoneNumber);

```

**Comment by atrofimenko** [comment]
> I re-verified the logic,
> as if there is no plus sign before the phone number, and no country provided,
> the logic will simply assume the country is USA.
> 
> To improve the detecting accuracy, please add a '+' sign before the phone number (if you're sure that the phone number always come with country code):
> 
> ```
> import phoneLib from 'phone';
> 
> const phoneNumber = '+12045552348';
> phoneLib(phoneNumber);
> ```

Thank you! It works for me.
