### ISSUE TITLE
Spanish country prefix not recognized without '+'

### ISSUE THREAD

**Issue by CiprianaM** [AfterShip/phone#204]
`const phone = require('phone');

const phoneNo = '34603123456'
const normalizedPhone = phone(phoneNo, '', true);
console.log(normalizedPhone, 'normalizedPhone');`

Output: [] normalizedPhone.

Thanks!

**Comment by Bossa573** [comment]
If there is no plus sign before the phone number, and no country provided,
the module logic will simply assume the phone number country is USA.

To improve the detecting accuracy, please add a '+' sign before the phone number (if you're sure that the phone number always come with country code):

```
const phone = require('phone');

const phoneNumber = '+34603123456';
phoneLib(phoneNumber);
```

or, if you already know the country, you just want to reformat the phone number to E.163 format:

```
const phone = require('phone');

const phoneNumber = '34603123456';
phoneLib(phoneNumber, 'ESP');
```
