### ISSUE TITLE
Why does this number not work?

### ISSUE THREAD

**Issue by watadarkstar** [AfterShip/phone#205]
**Phone Number:**

```
phone("2793339904")
```

**Expected**

```
["+12793339904", "USA"]
```

**Actual**

`[]`

**Comment by Bossa573** [comment]
please provide the detail, about what country, what is your expectex output

**Comment by watadarkstar** [comment]
@Bossa573 Here is the phone number lookup: https://www.whitepages.com/phone/1-279-333-9904

Added more details in the description but I'll add them here:

**Phone Number:**

```
phone("2793339904")
```

**Expected**

```
["+12793339904", "USA"]
```

**Actual**

`[]`

**Comment by watadarkstar** [comment]
I can submit a PR

**Comment by watadarkstar** [comment]
@Bossa573 I submitted a PR for this https://github.com/AfterShip/phone/pull/206 .

Note: (279) is a California (CA) area code

**Comment by Bossa573** [comment]
updated by the PR

**Comment by Bossa573** [comment]
released in https://github.com/AfterShip/phone/releases/tag/2.4.17
