### ISSUE TITLE
E.164 AWS SNS controversy

### ISSUE THREAD

**Issue by Jay-PC** [AfterShip/phone#208]
When we select US using your library, we end up with ["+1XXX5550100","USA"]. However, when AWS defines the same value in E.164 format for use in their SNS SMS send (https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/sns-examples-sending-sms.html), they specify that it must be +1001XXX5550100. If we add the extra "100" between the + and the 1 in your result, their service works. How can we get your function to format the appropriate E.164 for use with Amazon AWS SNS SMS services, please? Is there a way to add an extra parameter to get the extra required prefix or am I just missing something? Thanks.

**Comment by Bossa573** [comment]
from AWS the documentation:
```
Phone numbers that follow this format can have a maximum of 15 digits, and they are prefixed with the plus character (+) and the country code. For example, a US phone number in E.164 format would appear as +1001XXX5550100.
```
1. They stated "`can` have a maximum of 15 digits", do they mention the format of `+1001XXX5550100` is a `MUST`, or it's just an example?
2. I have never seen a proper E.164 US phone with an extra `100` prefix, do you have any extra documentation stated about this?
3. If you have ever tried a phone that `+1 + area code + phone number` does not work, but `+1 + 001 + area code phone number` works well for AWS SNS, please consult AWS technical support.
(There is no area code of  "001", https://www.allareacodes.com/area_code_listings_by_state.htm / https://en.wikipedia.org/wiki/Category:Area_codes_in_the_United_States)

**Comment by Jay-PC** [comment]
Thanks for your reply. And you are correct! It's incredible that AWS gave an example of +1001 for the US, and by the way... that works on their system! However, using Angular with your tool, we weren't initially getting the +1 for the US and the number failed. We assumed it was because of the difference in US code with AWS. Once we fixed the result from your tool, we found that +1 worked with AWS as well. NOTE: once we got everything working, we deployed the stack, which included Elastic Beanstalk node.js web serves. Everything stopped working! The answer is that you have to push a security update for the Elastic Beanstalk to use SNS. It's interesting that the same thing was not needed for SES use. Thanks again!

**Comment by Bossa573** [comment]
Thank you for the information, 
it's very weird that the number works well on SNS with +1001 prefix,
but as long as +1 works, it should not be an issue,
I will close this ticket now
