### ISSUE TITLE
Results without plus sign

### ISSUE THREAD

**Issue by elleryfamilia** [AfterShip/phone#218]
Currently, the library returns no results for this number as per your documentation:

85291234567

However, both [Twilio](https://www.twilio.com/console/lookup) and [this site](https://www.comfi.com/abook/reverse) are able to successfully return the correct country (HK). Wondering why that is

**Comment by Bossa573** [comment]
Please refer to this readme section
https://github.com/AfterShip/phone#without-country-code-and-no-phone-prefix

**Comment by Bossa573** [comment]
Note that if there is no plus sign provided, the module will assume the phone number is a USA or Canada phone number.
and then 85291234567 is not a valid mobile phone number for USA or Canada, hence no result will be returned
