### ISSUE TITLE
Twilio Magic Numbers Not Parsed

### ISSUE THREAD

**Issue by thelaughingwolf** [AfterShip/phone#221]
Twilio lists a variety of "magic numbers" for use in their sandbox: [see here](https://www.twilio.com/docs/iam/test-credentials). This library can't handle the only valid "from" number Twilio provides: **+15005550006** I have not tested any of the other numbers.

**Comment by Bossa573** [comment]
`5005550006`: this is not a valid mobile phone number (https://github.com/AfterShip/phone/blob/master/lib/iso3166Data.js#L17)
Please skip the testing if you know it's a Twilio magic number

**Comment by thelaughingwolf** [comment]
Ah, interesting. `500` is actually a valid area code, although it's not going to be a person's number.

We might have to hard-code all of Twilio's magic numbers, then.

Thanks for the quick response.
