### ISSUE TITLE
Invalid armenian mobile phone number with 033 code

### ISSUE THREAD

**Issue by hrachgalstyan** [AfterShip/phone#222]
Please add AM (Armenia) country code "033"

**Comment by Bossa573** [comment]
hello, please provide related reference / website / documents

**Comment by hrachgalstyan** [comment]
https://www.beeline.am/en/promos/2020/03/13/numbers-with-033-code-on-open-sale/257/
033******
+37433********

**Comment by Bossa573** [comment]
at the moment the mobile data supports 8 digit Armenian phone number only
https://github.com/AfterShip/phone/blob/master/lib/iso3166Data.js#L113
any document stated that it's supporting 10 digit? (as your example stated +374 `33********`)

**Comment by hrachgalstyan** [comment]
Yes it's okay, 33******

**Comment by hrachgalstyan** [comment]
8 digit

**Comment by Bossa573** [comment]
released https://github.com/AfterShip/phone/releases/tag/2.4.21, please verify,
and reopen this ticket if needed
