### ISSUE TITLE
ES6 module compatibility without flags

### ISSUE THREAD

**Issue by GabrielGil** [AfterShip/phone#223]
It would be great that this module is compatible with ES6 modules without the flag `esModuleInterop`. 

Currently the module can be imported on ES6 like this:

```js
import * as phone from 'phone';
```

However this produces this error:

```
This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag.
```

Enabling the compatibility flag you allow ES6 syntactically correct imports, however it just instructs the compiler to convert the CommonJS module so it can be imported with default:

```js
import phone from 'phone';
```

### Solution
The module could be CommonJS and ES6 compatible so it can be imported as:

```js
import phone from 'phone';
// or
import { phone } from 'phone';
```

Not a big difference, since only one function is exposed, however the second option allows to export different functions in case the API grows in the future.

**Comment by Bossa573** [comment]
Thanks for the report, since we are going to release a new major bump, this would be included in that release as well. I will close this issue for now, however this issue will be keep tracked by the label. Thank you very much.

**Comment by cloudjk** [comment]
On my end, above solution did not work. 

``
import phone = require('phone')
``

This worked for me.
