### ISSUE TITLE
Invalid parsing IDN phone number for 11 digit

### ISSUE THREAD

**Issue by restuhaqza** [AfterShip/phone#225]
I trying to parse the phone number for IDN (Indonesia) format with min length is 11 digit. but it's failed. 
```
const phone = require("phone")

let phoneNumber =  "628999525900"

const parsePhoneNumber = phone(phoneNumber, phoneNumber) // return [] expected it should ["+628999525900", "IDN"]
```

**Comment by Bossa573** [comment]
please note that the second parameter should be the country iso-3166 alpha 2 or alpha 3 code,
please refer to this section
https://github.com/AfterShip/phone#api

**Comment by restuhaqza** [comment]
Sorry, I mistake to write the issue. actually, I already input the second parameter with the alpha 3 code of Indonesia Country. but the return is empty array

**Comment by Bossa573** [comment]
Please refer to this section:
https://github.com/AfterShip/phone#without-country-code-and-no-phone-prefix

`62` is the country phone code of Indonesia,
if you know your phone number includes the country code,
please append `+` before the phone number, and become:

```
phone('+628999525900', 'IDN')
```

or you can enter the phone number without the `+` and `62`, like:

```
phone('8999525900', 'IDN')
```

which also work as well
