### ISSUE TITLE
phoneNumber in PhoneResult type is always typed to be `string` and not `string | null`

### ISSUE THREAD

**Issue by peterj35-dd** [AfterShip/phone#256]
In version 3.1.5   

Think the type signature of phoneNumber is a bit misleading as it always seems to be typed to string. Shouldn't it be `string | null`?

![image](https://user-images.githubusercontent.com/87710172/130267164-8aaf82e1-ff3c-4a11-97d4-dd493b079acd.png)

**Comment by Bossa573** [comment]
Hello @peterj35-dd, thanks for the reporting, while we're investigating this, if would be great if you got any recommendation for how to update the type, thank you very much

**Comment by Bossa573** [comment]
will close at the moment due to inactivity, please feel free to reopen
