### ISSUE TITLE
It Doesn't work for Brazilian phone number

### ISSUE THREAD

**Issue by magnuspedro** [AfterShip/phone#260]
Brazilian phone numbers have a particular rule, they are divided like.  `(Coutrnty code) (Area code) 9 (Number)`.
Every mobile phone must have 9 as first number, and 11 numbers including area code. Like `+55 11 9 88888888`
The land line has only 10 numbers including area code, so it's gonna be `(Coutrnty code) (Area code) (Number)`.

**Comment by Bossa573** [comment]
1. Can you provide some real examples of working phone number format and which does not work properly with this module?
2. Can you provide websites / wiki pages / docs showing above logics?

**Comment by magnuspedro** [comment]
For sure
1. This number `68632556587` is valid according to the module, but it cannot be because it has a six after area code instead of 9. A working phone example would be `11973837676`
2. I'm trying to find a doc with all the logic. I will post when finding it

**Comment by magnuspedro** [comment]
[This](https://www.teleco.com.br/num_cel.asp) is the best source I could find with mobile phone numbers explanation.
It's in Portuguese. If you need any assistance to translate it or any help, in general, I would be glad to help.

**Comment by Bossa573** [comment]
@magnuspedro can you help creating a PR to update the data directly?
https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts#L268
Thank you very much

**Comment by magnuspedro** [comment]
@Bossa573 For sure.  I will update as soon as possible

**Comment by magnuspedro** [comment]
I opened the PR
[https://github.com/AfterShip/phone/pull/261](https://github.com/AfterShip/phone/pull/261)

**Comment by Bossa573** [comment]
released https://github.com/AfterShip/phone/releases/tag/3.1.7 for including the changes, thanks
