### ISSUE TITLE
Hungarian phone numbers beginning with 50 fail validation

### ISSUE THREAD

**Issue by robwebdev** [AfterShip/phone#267]
According to [wikipedia](https://en.wikipedia.org/wiki/Telephone_numbers_in_Hungary#Mobile_phone_codes) Hungarian phone numbers may start with the digits `50` but in my tests this fails validation.

**Comment by Bossa573** [comment]
thanks for the report and it has been included in https://github.com/AfterShip/phone/releases/tag/3.1.10
