### ISSUE TITLE
Detect trunk prefix when country is specified

### ISSUE THREAD

**Issue by JamieDixon** [AfterShip/phone#268]
Hey folks. Thanks for your work on this library, it's really helpful and has saved me a lot of time.

One thing that I've had to handle myself is the case where a trunk value is included in a number and we set the country to a value in the options.

In https://github.com/AfterShip/phone/blob/50bfbc28e78a890d0c401b8318ec61cd91554b07/src/index.ts#L91 we basically skip the the bit of code that parses out the leading zero when the country is specified.

This means we need a wrapper around this library to detect whether a number has a `+` or leading `00` and strip out the country from the options. Sometimes users do enter their UK number as `+4407123 123 123` which this library reports as **invalid** if `options.country` is set to a value (e.g.`GB`) but it reports the same number as **valid** if there is no country specified in the options.

Is this something you'd accept a PR on or are there other reasons for this approach that I'm not aware of?

Thanks again for this library, you've done a great job and it's appreciated.

**Comment by Bossa573** [comment]
The fundamental logics of this module assumes there would not be a country code (no matter with plus sign or not) if you have to provide a country, we don't have any plan to modify this behavior, please do not pass the country parameter if `+` exist.
