### ISSUE TITLE
Allow Twilio magic numbers

### ISSUE THREAD

**Issue by JamieDixon** [AfterShip/phone#269]
Hey folks. Second time I'm here today. Thanks again for this great lib. I hope you don't mind me making these suggestions.

Twilio has a bunch of magic numbers that are technically valid and can send and receive messages. 

These numbers can be found [Here](https://www.twilio.com/docs/iam/test-credentials) and all contain a `+15` prefix. 

Could we add this prefix to the validation list so that Twilio numbers can be used? Would you accept a PR on this one?

Thank you!

**Comment by Bossa573** [comment]
Vendors testing phone number and fake numbers (say us number start from 555) would not be considered as part of the library as this will break the purpose of "validating if a number a valid mobile phone numnber"
please simply add "if phoneNumber.match(magicnumbers) then" logic in your application
