### ISSUE TITLE
Persist number when invalid result

### ISSUE THREAD

**Issue by JamieDixon** [AfterShip/phone#270]
Me again. Thank you for this library and for giving these suggestions a look-in.

Something I've come across when writing functional JS is that we lose the phone number when the result of validation is invalid.

See: https://github.com/AfterShip/phone/blob/50bfbc28e78a890d0c401b8318ec61cd91554b07/src/index.ts#L48

It would be really helpful if the number itself was persisted, even when `isValid` is `false`. This would help with validation messaging and would save me having to use a `State` monad or something to persist the value as the validation happens.

Something you'd accept a PR on or do you rely on the number being `null` when it's invalid?

**Comment by Bossa573** [comment]
phoneNumber is the key used for storing the phone number of the formatted result, and should not be used for other purpose and make it become ambiguous, therefore it won't be changed
