### ISSUE TITLE
Syntex error in IE 11

### ISSUE THREAD

**Issue by mohd999** [AfterShip/phone#272]
Its throwing syntax error in IE 11.
SCRIPT1010: Expected identifier
on other browser its working fine

**Comment by Bossa573** [comment]
Thank you for the report, however, no version of IE nor any non-modern web browser will be supported.

(And please move away from IE: https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/)
