### ISSUE TITLE
New zealand phone numbers failing

### ISSUE THREAD

**Issue by ricick** [AfterShip/phone#279]
https://codesandbox.io/s/js-example-forked-s28sb9?from-embed

`const { phone } = require("phone");
const result = phone("+64 3 442 6722", { country: "NZ" });
console.log(result.isValid);`

returns false

**Comment by Bossa573** [comment]
@ricick please provide docs / website / pdf etc showing that the provided phone number should be a valid phone number, thank you

**Comment by ricick** [comment]
just looked for some example nz numbers online. This example is this company:
https://www.heliski.co.nz/

**Comment by Bossa573** [comment]
@ricick note that only `mobile` phone number accepted
please refer to this
https://github.com/AfterShip/phone#skipping-phone-number-initial-digit-checking

**Comment by ricick** [comment]
ah my bad, sorry!

**Comment by Bossa573** [comment]
no problem, if you got any issue feel free to open another ticket, thanks for using the package
I'll close the ticket first
