### ISSUE TITLE
Transform mobile number in ARG

### ISSUE THREAD

**Issue by teddychan** [AfterShip/phone#28]
http://www.howtocallabroad.com/argentina/

http://www.howtocallabroad.com/results.php?callfrom=hong_kong&callto=argentina

![image](https://cloud.githubusercontent.com/assets/1013507/8349082/73230458-1b4c-11e5-8c50-d888cacb05a6.png)

![image](https://cloud.githubusercontent.com/assets/1013507/8349093/871455ca-1b4c-11e5-9203-c0c82c7aab6c.png)

**Comment by gpdeedler** [comment]
Great library and making it work with ARG would be very helpful!  Plus one on this ticket!

**Comment by Bossa573** [comment]
This issue should be outdated, please reopen if needed
