### ISSUE TITLE
Missing 743 Area Code

### ISSUE THREAD

**Issue by tomodocc** [AfterShip/phone#280]
Hi guys, 

Seems like the 743 area code isn't working even in the latest pull. Would you guys be able to add it please? 

Thanks!

**Comment by Bossa573** [comment]
@tomodocc hello, any sources / wiki / websites showing such `743` area code is valid?
and also, what country?

**Comment by tomodocc** [comment]
@Bossa573 Yes, [here is a link to a wiki](https://en.wikipedia.org/wiki/Area_codes_336_and_743#:~:text=Area%20codes%20336%20and%20743%20are%20NANPA%20area%20codes%20which,Foothills%20and%20northern%20Mountain%20regions.). 

United States. 

Thanks!

**Comment by Bossa573** [comment]
Released https://github.com/AfterShip/phone/releases/tag/3.1.13 for adding 743 to US, thanks for the report
