### ISSUE TITLE
Missing 726 Area Code

### ISSUE THREAD

**Issue by tomodocc** [AfterShip/phone#281]
[Wikipedia to Area Code.](https://en.wikipedia.org/wiki/Area_codes_210_and_726#:~:text=Area%20codes%20210%20and%20726%20are%20area%20codes%20for%20telephone,and%20near%20San%20Antonio%2C%20Texas.)

Hello, there seems to be an error when I try to verify this number. 

Would anyone be able to help with this? 

Thank you!

**Comment by Bossa573** [comment]
@tomodocc please provide sample input and sample out to replicate the result

**Comment by tomodocc** [comment]
@Bossa573 [Here is an example](https://replit.com/@DarylOcc1/WiltedSpiritedDiscussion#index.js). 

Thank you!

**Comment by Bossa573** [comment]
This should be included in the update https://github.com/AfterShip/phone/releases/tag/3.1.14, please verify and reopen the ticket if needed
