### ISSUE TITLE
Some old italian land number fails

### ISSUE THREAD

**Issue by costafrancesco94** [AfterShip/phone#293]
`+39 049 XXX XXX` (where x could be every digit from 0 to 9) can be a valid land number in italy.

We have prefixes for land number as well, they can vary from 2 to 4 digits (049 is for Padova province, 0444 Vicenza, 0424 Treviso, 02 Milano... etc).

Problem is when you imput that without specifing italian country it get recognized, but when you specify the country (IT) it is considered invalid.

Problem may be the leading 0 that actually is required for the number and not optional (without it, phone would be invalid)

**Comment by Bossa573** [comment]
Note that the module does not have the capability to recognize landline numbers, this would not be supported.
Please check https://github.com/AfterShip/phone#skipping-phone-number-initial-digit-checking and set validateMobilePrefix to false if needed
