### ISSUE TITLE
New Oklahoma City area code is considered invalid

### ISSUE THREAD

**Issue by chas-klaviyo** [AfterShip/phone#299]
Hey all, tried to put up a PR to fix this, but wasn't able to get git access to push.

Love your package, but realized recently that there's a [new area code for the Oklahoma City](https://kfor.com/news/local/welcome-the-572-area-code-to-central-oklahoma/#:~:text=OKLAHOMA%20CITY%20(KFOR)%20%E2%80%93%20The,the%20classic%20405%20area%20code.&text=This%20means%20that%20all%20callers,their%20cell%20phones%20or%20landlines.) that doesn't appear to be supported by your package.

I was going to add it to this array here https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts#L7 .

Please let me know if I can assist at all or if there is any timeline for getting this updated!

**Comment by Bossa573** [comment]
Thanks for the report and updated here:

https://github.com/AfterShip/phone/releases/tag/3.1.21
https://www.npmjs.com/package/phone/v/3.1.21
