### ISSUE TITLE
[Bug/ problem report] Missing city code '672' of Canada

### ISSUE THREAD

**Issue by 5kahoisaac** [AfterShip/phone#300]
I used this library for formating phone number `16725146482` with the country `CA`, it returns `{ isValid: false, ... }`

According to [wikipedia](https://en.wikipedia.org/wiki/Area_codes_778,_236,_and_672), the `+1-672` should be a valid starting of Canada's phone number therefore I checked the [source data for Canada](https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts#L330).

I found that the `mobile_begin_with` of `CA` is based on [countrycode.org](https://countrycode.org/canada) and it missed the area code `672`.

**Comment by Bossa573** [comment]
released https://github.com/AfterShip/phone/releases/tag/3.1.22
