### ISSUE TITLE
[Problem] phone number with country field can't recognize without starting with + 

### ISSUE THREAD

**Issue by 5kahoisaac** [AfterShip/phone#303]
Those of the following number aren't work useless I add `+` symbol before the phone number.

```
phone('436763394389', { country: "AT" })
phone('043 664 5204669', { country: "AT" })
phone('0043 676 3394389', { country: "AT" })
/* {isValid: false, phoneNumber: null, countryIso2: null, countryIso3: null, countryCode: null} */

phone('+436763394389', { country: "AT" })
phone('+043 664 5204669', { country: "AT" })
phone('+0043 676 3394389', { country: "AT" })
/* {isValid: true, phoneNumber: "+436763394389", countryIso2: "AT", countryIso3: "AUT", countryCode: "+43"} */
```

**Comment by 5kahoisaac** [comment]
The above cases is only a demo, this issue happen in non "AT" country too.

**Comment by Bossa573** [comment]
https://github.com/AfterShip/phone/blob/master/README.md#with-country-code--phone-prefix-but-no--sign

if you know the input phone number got country prefix, please add the plus sign `+`.

i.e.
```
phone('6763394389', { country: "AT" })
phone('664 5204669', { country: "AT" })
phone('676 3394389', { country: "AT" })
```
or
```
phone('+436763394389', { country: "AT" })
phone('+43664 5204669', { country: "AT" })
phone('+43676 3394389', { country: "AT" })
```

but no 

```
phone('436763394389', { country: "AT" })
phone('43664 5204669', { country: "AT" })
phone('43676 3394389', { country: "AT" })
```

This is the known limitation of the library

**Comment by 5kahoisaac** [comment]
The problem is the phone number format is uncontrollable and the response of the package is sync, for example: 
```
phone('85298765432', { country: 'HK' })
/* {isValid: true, phoneNumber: "+85298765432", countryIso2: "HK", countryIso3: "HKG", countryCode: "+852"} */
```

The response is not same to "AT", it can recognize without starting with +

**Comment by Bossa573** [comment]
kind of edge case,
take `85298765432` and `hk` as an example, 
here: 
https://github.com/AfterShip/phone/blob/master/src/index.ts#L83

processedPhoneNumber = 85298765432, hence processedPhoneNumber.length = 11,
however `foundCountryPhoneData.phone_number_lengths = [8]`,
therefore it won't run `line 84` and will not add the country code prefix before the phone number,

And then here, https://github.com/AfterShip/phone/blob/master/src/index.ts#L117
and here https://github.com/AfterShip/phone/blob/master/src/lib/utility.ts#L135,
it will remove the `852` before the phone number, and become 98765432, 
a proper hong kong mobile phone number that matches the specification of `foundCountryPhoneData`, 
hence it works.

---

for `436763394389` and `at`,
similarly at https://github.com/AfterShip/phone/blob/master/src/index.ts#L83,
processedPhoneNumber = 436763394389,  processedPhoneNumber.length = 12,
however `foundCountryPhoneData.phone_number_lengths: [ 10, 11, 12, 13, 14]`
and therefore `line 84` executed and `processedPhoneNumber` become `4343`6763394389,
and hence breaks all the logics afterward.

however, this logic would not be updated at the moment. If you know your input got the country code, then simply pad a `+` before the input, and it should work
