### ISSUE TITLE
Zambian phone numbers starting with 7 are not supported

### ISSUE THREAD

**Issue by MarkNjunge** [AfterShip/phone#306]
Zambia has phone numbers starting with either `9` or `7`. The library currently only supports `9`.
https://en.wikipedia.org/wiki/Telephone_numbers_in_Zambia

We had a user authenticate on Firebase using `+26076...` so it's definitely valid.

**Comment by Bossa573** [comment]
Hello, thanks for the reporting, would you mind creating a PR for the above fix? thank you very much

**Comment by Bossa573** [comment]
https://github.com/AfterShip/phone/releases/tag/3.1.24
