### ISSUE TITLE
[Bug/ problem report] Brazilian numbers can also have 10 digits

### ISSUE THREAD

**Issue by ana-vf** [AfterShip/phone#308]
Hello, 
It appears that some Brazilian numbers can also have 10 digits, however the rules in phone library would only allow 11 digit numbers.
as discovered here https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts#L278
Is this something you can adjust? Alternatively, is there a way to locally override the rules phone library is using?
Thanks :)

**Comment by Bossa573** [comment]
Hello, thanks for the report, however is there any reference showing that Brazillian mobile phone number got 10 digit?

**Comment by ana-vf** [comment]
hey @Bossa573 
I found this [Telephone numbers in Brazil](https://en.wikipedia.org/wiki/Telephone_numbers_in_Brazil)
We do have an example phone number that is in this format `+5511-xxxx-xxxx` that was failing to pass validation, however is a working number.
Thanks!

**Comment by Bossa573** [comment]
thanks for the reference, @ana-vf would you mind creating a PR for this?

**Comment by ana-vf** [comment]
thanks @Bossa573 here is the PR https://github.com/AfterShip/phone/pull/309
