### ISSUE TITLE
Format for Somalia is out of date.

### ISSUE THREAD

**Issue by williamli** [AfterShip/phone#310]
According to https://en.wikipedia.org/wiki/Telephone_numbers_in_Somalia, the number format for Somalia should be updated to support the following:

![CleanShot 2022-08-24 at 11 27 03](https://user-images.githubusercontent.com/179761/186322251-7c1578c4-e6d0-4d2d-ad7b-983c8cfe1f8a.png)

I will submit a PR.

**Comment by Bossa573** [comment]
@williamli Thank you for the report, and yes if possible please submit a PR

And also, please do not push comments to those very old PR or tickets.
That PR was created 6 years ago, and the new comments will notify the contributors in that ticket who don't have much context.
Please keep the conversation in the new tickets here.

**Comment by Bossa573** [comment]
https://github.com/AfterShip/phone/releases/tag/3.1.26
