### ISSUE TITLE
when i use phone('8999525900', 'IDN') i get error

### ISSUE THREAD

**Issue by cumthxy** [AfterShip/phone#314]
when i use phone('8999525900', 'IDN') i get 
{isValid: false, phoneNumber: null, countryIso2: null, countryIso3: null, countryCode: null}

**Comment by Bossa573** [comment]
https://github.com/AfterShip/phone#2-with-country

Please follow the usage precisely,
NOT `phone('8999525900', 'IDN')`
it's `phone('8999525900', {country: 'IDN'})`
