### ISSUE TITLE
Lebanon Phone Number returns invalid

### ISSUE THREAD

**Issue by lnabil** [AfterShip/phone#315]
I have a customer trying to register with his phone number from lebanon, but phone returns isValid = false although it's a valid number
the number starts with: +961813XXXXX

Please advise

**Comment by Bossa573** [comment]
from the data https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts#L956 
only the number start with `3` or `7` are supported
please attach any document / website / information shows that `8` is a valid mobile phone number prefix

**Comment by lnabil** [comment]
i checked here and it shows the number is valid
https://freetools.textmagic.com/phone-validator
try a number starts with 813
+961813XXXXX

**Comment by Bossa573** [comment]
Cannot judge the reliability of the source, any wiki page / web page / government web page indicating that?
note that we do not accept landline data (if the number prefix of landline number and mobile phone number are different)

**Comment by lnabil** [comment]
i added his mobile number and contacted via whatsapp. it's a mobile number

**Comment by lnabil** [comment]
i will try to search for any legal website that indicates that

**Comment by lnabil** [comment]
https://en.wikipedia.org/wiki/Telephone_numbers_in_Lebanon
you will find here mobile operators start with 3,7,8

**Comment by Bossa573** [comment]
ok will add `8`

**Comment by Bossa573** [comment]
https://www.npmjs.com/package/phone/v/3.1.28
