### ISSUE TITLE
Swiss fixed phone numbers marked as invalid

### ISSUE THREAD

**Issue by eveningforgery** [AfterShip/phone#319]
Hello there, awesome lib! 🎉 

I'm getting some issues with all of those formats marked as invalid.
+41 (0)21 XXX XX XX
+41 (0)22 XXX XX XX
+41 021 XXX XX XX
+41 21XXXXXXX
+41021XXXXXXX

21 represents a specific canton, here is the list of all national destination codes:
https://en.wikipedia.org/wiki/Telephone_numbers_in_Switzerland

No issues with swiss mobile phone numbers so far.

**Comment by Bossa573** [comment]
https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts#L341

this is the current allowed set of Switzerland mobile phone number prefix, 
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/1013526/196404314-461f28aa-bcd7-48a0-aee8-db4b4defea69.png">
If i understand the wiki page correctly, the data should be correct right?

**Comment by eveningforgery** [comment]
After further testing, this is correct. I went a bit too fast, my bad.

Thank you for double checking.

**Comment by Bossa573** [comment]
thank you for confiming
