### ISSUE TITLE
Support for Curaçao

### ISSUE THREAD

**Issue by stefanvucic** [AfterShip/phone#320]
Hello team. 
We are successfully using the **phone** library for some time but a few days ago we faced an issue with the phone number for the country Curaçao. Just wondering if this is a known issue and if there is any plan for supporting Curaçao? 

Please refer to the provided images. Thanx in advance!

<img width="208" alt="image" src="https://user-images.githubusercontent.com/89129662/196923038-9111c0dc-705f-4752-af63-2cb6bf2a970f.png">

<img width="145" alt="image" src="https://user-images.githubusercontent.com/89129662/196923084-09d551d0-de97-47fd-bc49-54fb476d7cca.png">

**Comment by Bossa573** [comment]
Hello,
the data structure would be like this: https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts

```
{
		alpha2: 'CW',
		alpha3: 'CUW',
		country_code: '5999',
		country_name: 'Curaçao',
		mobile_begin_with: ['5', '6'],
		phone_number_lengths: [7]
},
```

Reference:
https://www.curacao.com/en/questions/internet-connection-and-cell-service/what-is-the-telephone-code-in-curacao

See if the above setting make sense to you @stefanvucic

**Comment by stefanvucic** [comment]
Hello, thanks for the quick reply! I assume this is fine. 
We will need to update the phone package version after those changes are applied?

**Comment by Bossa573** [comment]
yes if it's fine I'll update and bump the version

**Comment by stefanvucic** [comment]
Absolutely! If it is not a problem just send a new version here once it is ready.

**Comment by Bossa573** [comment]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/1013526/196927151-dc95900d-ef2f-46f3-8b8a-f31dd163706c.png">

https://github.com/AfterShip/phone/releases/tag/3.1.29

https://www.npmjs.com/package/phone/v/3.1.29

the new version is readu

**Comment by stefanvucic** [comment]
Thanks a lot!
