### ISSUE TITLE
US mobile_begin_wit has duplicated code

### ISSUE THREAD

**Issue by bright-seasalt** [AfterShip/phone#321]
I found '463' mobile_begin_with code of US is duplicated. Maybe one of them needs to be removed? 
https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts

![image](https://user-images.githubusercontent.com/101028288/197386583-b533ce71-c1ec-4969-815c-58fa411a6712.png)

**Comment by Bossa573** [comment]
thanks for the report and yes supposedly should not be repeated (it should not affect the module capability though)
would you create a PR for this one?

**Comment by bright2227** [comment]
PR is [here](https://github.com/AfterShip/phone/pull/322).
Sorry, I have to use my private account because [bright-seasalt](https://github.com/bright-seasalt) is only for my job.

**Comment by Bossa573** [comment]
Thank you very much for the PR and this would be included in the upcoming release.
