### ISSUE TITLE
Austrailian phone number failing validation

### ISSUE THREAD

**Issue by acoyfellow** [AfterShip/phone#323]
Hi there, thank you for all of the hard work on this library.

I'm not sure if this is expected behavior, or a bug.. But when using an Austrailian phone number, the `+` seems to be required.

```js
const { phone } = require('phone');
console.log(phone('481843851')); // fail
console.log(phone('0481843851')); // fail
console.log(phone('61481843851')); // fail
console.log(phone('+61481843851')); // pass
```

Reproduction: https://replit.com/@acoyfellow/node-playground-1#index.js

**Comment by Bossa573** [comment]
```
console.log(phone('481843851'));
console.log(phone('0481843851'));
```

Please refer to https://github.com/AfterShip/phone#3-without-country-code-and-no-phone-prefix

```
console.log(phone('61481843851'));
```

Please refer to https://github.com/AfterShip/phone#4-with-country-code--phone-prefix-but-no--sign
