### ISSUE TITLE
New area codes 656 and 771

### ISSUE THREAD

**Issue by miguelvelasquez** [AfterShip/phone#327]
The library is missing two US area codes that have been created in the past 2 years.
* 656 - https://www.cbsnews.com/miami/news/tampa-area-phone-changes-teed-up/#:~:text=TALLAHASSEE%20(CBSMiami%2FNSF)%20%2D,Public%20Service%20Commission%20announced%20Wednesday.
* 771 - https://dcpsc.org/The-District-of-Columbia-has-a-new-overlay-area-co.aspx#:~:text=The%20District%20of%20Columbia%20used,without%20an%20additional%20area%20code.

Can these be added please?

**Comment by miguelvelasquez** [comment]
Sure can, do I need access rights to create a PR for this repo?

**Comment by Bossa573** [comment]
please fork the repo to your github account, and create the PR

**Comment by miguelvelasquez** [comment]
Thanks, PR created https://github.com/AfterShip/phone/pull/328

**Comment by Bossa573** [comment]
Thanks for the PR and was merged

**Comment by Bossa573** [comment]
https://www.npmjs.com/package/phone?activeTab=versions
