### ISSUE TITLE
Valid Dutch numbers fails verification

### ISSUE THREAD

**Issue by mariorodriguespt** [AfterShip/phone#332]
https://receive-sms-online.info/3197010517412-Netherlands

<img width="285" alt="image" src="https://user-images.githubusercontent.com/1017581/209330082-84971330-ec97-4e70-8f51-57e4c2235f1a.png">

**Comment by Bossa573** [comment]
the website is not a reliable source showing the standard Netherland mobile phone number format, and it does not show the format either.

Please reopen if you found a source clearly showing the format, thank you

**Comment by mariorodriguespt** [comment]
@Bossa573 The website https://veriphone.io/ validates the phone number posted above as valid.

**Comment by Bossa573** [comment]
but it does not show a conclusive format
can you find a source shows:
1. how many digits expected for a Dutch mobile phone number
2. what is the expected prefix for a Dutch mobile phone number
