### ISSUE TITLE
Encountered some invalid phone numbers, please troubleshoot

### ISSUE THREAD

**Issue by meigesir** [AfterShip/phone#333]
some invalid phone numbers

1. +225 41 09 10 02
2. +232 31 272075

**Comment by Bossa573** [comment]
Hello, 

please provide related documentation or websites, showing that the above phone numbers should be a valid **mobile phone number** format, thank you

**Comment by Bossa573** [comment]
closing the ticket until further confirmation. Feel free to leave comment and reopen if you got further info

**Comment by meigesir** [comment]
> Hello,
> 
> please provide related documentation or websites, showing that the above phone numbers should be a valid **mobile phone number** format, thank you

Hello, this is the phone number on WhatsApp.

**Comment by Bossa573** [comment]
While I don't quite get your meaning of "a phone number on WhatsApp",
this library is intended to support mobile phone number only, thank you.
