### ISSUE TITLE
function to get the area code

### ISSUE THREAD

**Issue by leopucci** [AfterShip/phone#334]
Hey there! Nice lib!
I was wondering if there is a way to get the area code isolated from the number
Thanks

**Comment by Bossa573** [comment]
Thanks for the support, unfortunately, the lib does not have the feature to return the area code, as for most of the countries, the dataset only contains the first number after the country code (https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts#L102),
moreover some regions do not have an area code,
hence the behavior would be very inconsistent.
