### ISSUE TITLE
Missing Canada 782 area code

### ISSUE THREAD

**Issue by QuaidBartolomei** [AfterShip/phone#335]
I noticed that the 782 area code for Canada is missing:
https://www.cbc.ca/news/canada/nova-scotia/new-782-area-code-coming-to-n-s-p-e-i-1.1205298

**Comment by Bossa573** [comment]
thank you for the PR and it would be included in the next release

**Comment by Bossa573** [comment]
https://www.npmjs.com/package/phone/v/3.1.33
