### ISSUE TITLE
`phone('+441471323991').isValid` returns false?

### ISSUE THREAD

**Issue by baptisteArno** [AfterShip/phone#344]
If I'm being correct, this number: "+441471323991" should be valid?

But the library does not correctly validate it.

**Comment by Bossa573** [comment]
https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts#L635
according to the above line,
the library only considers +44 and following by 10 digits starting with `7` as a valid UK phone number,
i.e. `+447xxxxxxxxx`
please provide related documents showing that `1` is a valid `mobile` phone number prefix
(landline or other phone numbers formats are not intended to be included in this library)

Please feel free to reopen the ticket if needed, thank you very much.
