### ISSUE TITLE
Does not correctly parse Zimbabwe numbers +263

### ISSUE THREAD

**Issue by rayteale** [AfterShip/phone#350]
Version 3.1.31

Does not seem to recognise valid Zimbabwe numbers. 
1. Cresta Hotel in Harare
+263 24 2772633 : {
  isValid: false,
  phoneNumber: null,
  countryIso2: null,
  countryIso3: null,
  countryCode: null
}

2. By contrast Mojo Hotel in Cape Town
+27 87 940 7474 : {
  isValid: true,
  phoneNumber: '+27879407474',
  countryIso2: 'ZA',
  countryIso3: 'ZAF',
  countryCode: '+27'
}

**Comment by Bossa573** [comment]
note that the library cannot detect landline phone numbers properly.
https://github.com/AfterShip/phone#faq
thank you very much

**Comment by rayteale** [comment]
Not just landline numbers.   Also fails with eSim mobile numbers.  i havent tested with other Zim mobiles.

**Comment by Bossa573** [comment]
Can you provide the precise correct format (and the prove showing those are the correct mobile phone number format)?

**Comment by Bossa573** [comment]
Format refering to 
https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts#L1896

mainly about phone number prefix and the phone number length

**Comment by rayteale** [comment]
My customer complained with a number [+263 78 589 xxxx].  Apparently this is an eSim number in Zimbabwe.  My application is for mobiles only.   Perhaps they have recently added 78 to mobile area codes. Unfortunately I am not in that country so cant test at all.

**Comment by rayteale** [comment]
Apparently 78 is valid mobile for Zimbabwe - according to Wikipedia.   Econet Wireless Zimbabwe.    See "How to call a Zimbabwe mobile phone number" on this page  https://en.wikipedia.org/wiki/Telephone_numbers_in_Zimbabwe

**Comment by Bossa573** [comment]
I'll add 78 to it in the next release

**Comment by Bossa573** [comment]
https://github.com/AfterShip/phone/releases/tag/3.1.37
https://www.npmjs.com/package/phone/v/3.1.37
