### ISSUE TITLE
Issue with Bahrain country code

### ISSUE THREAD

**Issue by pdm-nagarro** [AfterShip/phone#355]
Hi Team,

I am getting mobile number is invalid when entering bahrain number starting with "6", for the number starting with "3" are working fine but not with "6"

I added validateMobilePrefix, but in that scenerio, if i am adding any invalid number like "111111", its taking it as a valid number.

**Comment by Bossa573** [comment]
Hello, please provide:
1. real sample input (dummy phone number is fine, don't leave personal info)
2. the expected output
3. reference docs / website showing that the phone number format should be valid

**Comment by levenx** [comment]
i had the same problem.

**Comment by Bossa573** [comment]
closing the ticket due to inactivity
for any report, please provide the detail as stated above
please feel free to reopen the ticket if needed
