### ISSUE TITLE
Library incorrectly flagging UAE phone numbers as incorrect

### ISSUE THREAD

**Issue by codan84** [AfterShip/phone#359]
An example of correct phone number: `+97148376525`
Output of using `phone`:
```
> phone('+97148376525', { validateMobilePrefix: false })
{
  isValid: false,
  phoneNumber: null,
  countryIso2: null,
  countryIso3: null,
  countryCode: null
}
> phone('+97148376525')
{
  isValid: false,
  phoneNumber: null,
  countryIso2: null,
  countryIso3: null,
  countryCode: null
}
> phone('+97148376525', { country: 'ARE', validateMobilePrefix: false })
{
  isValid: false,
  phoneNumber: null,
  countryIso2: null,
  countryIso3: null,
  countryCode: null
}
```

**Comment by codan84** [comment]
Example using https://www.npmjs.com/package/google-libphonenumber
```
> const phoneUtil = require('google-libphonenumber').PhoneNumberUtil.getInstance();
undefined
> phoneUtil.isValidNumberForRegion(phoneUtil.parse('+97148376525', 'AE'), 'AE')
true
```

**Comment by codan84** [comment]
Data in the link provided must be wrong. The phone number I posted in my initial message is a callable, correct Dubai phone. Go ahead and try it.

**Comment by Bossa573** [comment]
The URL above is indeed the source data of this repo.
And also, please provide any proof / website / pdf showing the phone number format guidelines.
It's unable to know the accurate format of the phone number you provide.
And it is not practical to actually try every phone number in the world.

**Comment by codan84** [comment]
https://github.com/google/libphonenumber/blob/master/resources/metadata/971/comments.csv
https://www.itu.int/oth/T02020000DC/en
https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000DC0001PDFE.pdf
  
Clearly phone numbers can be 8 digit. The source you are using is outdated.

**Comment by codan84** [comment]
Furthermore, looking at NDC (800), numbers can be between 5 and 12 digits long

**Comment by Bossa573** [comment]
Further digging out from the wiki page
https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Arab_Emirates


## Landline
0x xxx xxxx  (8-digits excluding thunk code `0`)

## Mobile
05x xxx xxxx (9-digits excluding thunk code `0`)

----

This is also align to the data source you provided: https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000DC0001PDFE.pdf
The `phone` only supports mobile phone number, not landline,
we would not include those formats to the library.
(Refer to readme: https://github.com/AfterShip/phone#help)
