### ISSUE TITLE
Library does not recognise Swaziland Country Code +268

### ISSUE THREAD

**Issue by tariromukute** [AfterShip/phone#364]
Hi, thank you for this library.

I am using it to get the country for users accessing a chatbot via WhatsApp. Since the phone number come via WhatsApp, it's safe to assume they are all valid number. I have noticed that the library:
- [ ] does not recognise +268 phone numbers see [document](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000C60003PDFE.pdf)
- [ ] does not recognise some phone numbers from Botswana +267778xxxxx see [Page 7](https://www.itu.int/dms_pub/itu-t/oth/02/02/T020200001C0007PDFE.pdf)
- [ ] does not recognise some phone numbers from Malawi +265984xxxxxx [Last page](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000800002PDFE.pdf)
- [ ] does not recognise some phone numbers from Zimbabwe +263864xxxxxxx, see [Page 6](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000E90004PDFE.pdf)

**Comment by Bossa573** [comment]
hello, for all reports, please include the reference information such as PDFs, websites, etc. Thank you very much.

**Comment by tariromukute** [comment]
> hello, for all reports, please include the reference information such as PDFs, websites, etc. Thank you very much.

Hi @Bossa573, I am not sure I understand this. Do you mean the link to the application I am using the library with. Or you means some ISO standards to documentation.

**Comment by Bossa573** [comment]
any docs works, like each countries government official docs / website, wiki pages, or even 3rd party references showing your number format should be the valid **mobile** phone number formats.

**Comment by tariromukute** [comment]
Ohk noted. I found the ITU portal with the documents per country, see [link](https://www.itu.int/oth/T0202.aspx?lang=en&parent=T0202). I have also updated the issue with the links and page number for each set of phone numbers not being recognised.

**Comment by Bossa573** [comment]
1. for +268, I found that there's no data in the lib (https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts#L1633)
2. for +267, can add '77', '78' and '79' prefix (https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts#L312C48-L312C50)
3. for +265, the docs show 77, 88, 99 prefix, which match our data (https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts#L1211)
![image](https://github.com/AfterShip/phone/assets/1013526/d74505c0-9ca2-45b8-b34a-9491cd0c4134)
the doc doesn't seem to show +265-984xxxxxx is a correct format
4. for +263, 864xxxxxxx is the range of VoIP, which does not include in our lib's scope

**Comment by tariromukute** [comment]
Hey @Bossa573, thanks for checking the documents out. 
3. How will do a further search later, maybe the document is not up to date
4. I am guessing it is possible for someone to create a WhatsApp account using VOIP, if they select the option to verify via a call. I probably have to find a work around on this one, probably for a phone number that the package undefined for `phone('+263xxxxx').countryIso2?.toLowerCase()` I check if the number starts with +263.

**Comment by Bossa573** [comment]
https://www.npmjs.com/package/phone/v/3.1.40
handle (1) and (2)

upcoming updates for the new format, if possible please try to create the PR as well, thank you very much.

**Comment by tariromukute** [comment]
> https://www.npmjs.com/package/phone/v/3.1.40 handle (1) and (2)
> 
> upcoming updates for the new format, if possible please try to create the PR as well, thank you very much.

Thank you @Bossa573! Sure no problem, I will raise a PR for 3 or 4 depending on the information I find. Cheers.
