### ISSUE TITLE
Error in validating indian phone number with 11 digits

### ISSUE THREAD

**Issue by ykgw-santosh** [AfterShip/phone#365]
Hi, 

In India 10 digit is the max phone number allowed. But when we enter the 11 digit number (e.g. +9198242565487) it is still showing as a valid number. 
![image](https://github.com/AfterShip/phone/assets/53090715/a4600916-9631-44a1-8e23-3c91c5dc0360)

In the validation process, it removing the first 9 (+91**9**8242565487) from the number and remaining number(+918242565487) it shows as valid. Could you please look into it?

**Comment by Bossa573** [comment]
for such case please check https://github.com/AfterShip/phone#6-trunk-code-detection-logic and set `strictDetection` to true, thank you

**Comment by ykgw-santosh** [comment]
Thank you so much for the info @Bossa573 :-)
