### ISSUE TITLE
[Phone number format] Add more Poland prefix phone number

### ISSUE THREAD

**Issue by devmws** [AfterShip/phone#369]
Hello,

We found some of Poland number are not registered on the `mobile_begin_with`. Such as prefix +483xx are not on the list. For now, only `4`, `5`, `6`, `7`, `8` was on the list. It should also cover for `481` `482` `483` and `489`.

Reference:
https://en.wikipedia.org/wiki/Telephone_numbers_in_Poland

**Comment by Bossa573** [comment]
Hello, please provide a complete sample phone number for investigation

2023年11月3日(金) 13:09 devmws ***@***.***>:

**Comment by devmws** [comment]
Hello,

For example, this phone number was a valid phone number from Poland

+48338881574

Thank you.

**Comment by Bossa573** [comment]
<img width="740" alt="image" src="https://github.com/AfterShip/phone/assets/1013526/3c2fc338-a45c-4f2e-9f35-32223340be61">

from the wiki, 3 is not part of mobile phone number, will not modify.

https://github.com/AfterShip/phone#help

**Comment by devmws** [comment]
> <img alt="image" width="740" src="https://user-images.githubusercontent.com/1013526/280192754-3c2fc338-a45c-4f2e-9f35-32223340be61.png">
> from the wiki, 3 is not part of mobile phone number, will not modify.
> 
> https://github.com/AfterShip/phone#help

It is the Poland phone number. See this table

<img width="280" alt="image" src="https://github.com/AfterShip/phone/assets/149755207/1e6fd2a4-d438-43a5-be79-8a58edc23348">

As an additional reference, the prefix is for a city in Poland called Biała Podlaska

https://en.wikipedia.org/wiki/Bia%C5%82a_Podlaska

**Comment by Bossa573** [comment]
No matter if it's a Poland phone number or not, the library will only support MOBILE phone number format. No landline phone number format (or any other phone number format) will be included.

<img width="401" alt="image" src="https://github.com/AfterShip/phone/assets/1013526/ec6b5a50-ef6a-4f1e-96eb-d9048ad67ae5">

**Comment by thomasmoon** [comment]
Hi!

This seems like a very healthy and active library that I would easily choose as part of critical business software, but I need the same parsing that will work reliably for any phone number, not just mobile numbers.

Is there a similar library that will work for all phone numbers in the world that is as well maintained as this one?

**Comment by Bossa573** [comment]
@thomasmoon maybe you can try google one https://github.com/google/libphonenumber/
but I haven't try it, not sure if it's fully covering all phone numbers though

**Comment by thomasmoon** [comment]
Thanks @Bossa573, I eventually found my way there too. A bigger library with a few more features that I wouldn't really need but seems like a good option and also well maintained. Cheers!
