### ISSUE TITLE
Phone Number Output

### ISSUE THREAD

**Issue by jared-leddy** [AfterShip/phone#371]
Having a standard for how the number is stored in the DB is a great problem to solve. Unfortunately, those standards don't help with the front-end of a website or application. 

Your Docs Example:
```js
// input
const isValid = phone('(817) 569-8900', {country: 'USA'});
// output
{ 
   isValid: true, 
   phoneNumber: '+18175698900', 
   countryIso2: 'US', 
   countryIso3: 'USA', 
   countryCode: '+1'
}
```

For stuff like phone number validation and DB storage, this works perfectly. The public layer, is where we need some love on this package. We need the ability to retrieve the phone number and output it in the native country's format.

Here is an example using the Docs data from above. 
```js
// input
const isValid = phone('(817) 569-8900', {country: 'USA'});
// output, corrected for this example
{ 
   isValid: true, 
   phoneNumber: '8175698900',
   phoneNumberInternational: '+18175698900',
   phoneNumberFormatted: '(817) 569-8900',
   phoneNumberFormattedInternational: '+1 (817) 569-8900',
   countryIso2: 'US', 
   countryIso3: 'USA', 
   countryCode: '+1'
}
```
Example App Usage (TS React):
This is a pretty basic example of the usage, but we want the formatted output. 
```ts
import phone from 'phone';

interface Props {
  phone: string;
  countryIso2: string;
}

class ContactInfo extends React.Component<Props> {
  constructor(props: Props) {
    super(props);
  }
  render() {
    return (
      <div>
        // awesome react TSX
        <p>Phone: { phone( this.props.phone, 
            { country: this.props.countryIso2 } 
          ).phoneNumberFormattedInternational }
        </p>
        // awesome react TSX
      </div>
    );
  }
}
```

**Comment by Bossa573** [comment]
Thank you for the suggestion, however the main goal of this module is always `returning E.164 standard format`, it is not intend to return a localized format for displaying, moreover, the module does not have such capability to return the corresponding local format of each country.
