### ISSUE TITLE
Some valid phone number is getting as invalid phone numbers

### ISSUE THREAD

**Issue by saisanthosh23** [AfterShip/phone#372]
I'm validating US phone numbers starting with 84099xxxxx, getting an error as it's invalid phone numbers, whereas when we try it with other validators like google phone-lib or ngx-intl-tel-input - It's a valid phone number.

Basically we're validating a phone number in UI with **ngx-intl-tel-input**, and in backend nodejs with **npm phone**. From which npm phone is not supporting few phone numbers. Below error response 

`Object {isValid: false, phoneNumber: null, countryIso2: null, countryIso3: null, countryCode: null}`

**Comment by Bossa573** [comment]
Hello, can you make sure it's a mobile phone number, not a landline phone
number?

2023年12月26日(火) 17:20 saisanthosh23 ***@***.***>:

**Comment by Bossa573** [comment]
<img width="515" alt="image" src="https://github.com/AfterShip/phone/assets/1013526/81a2a6f9-7be2-41c8-a6c2-9a04804e3bf8">

cannot replicate with the phone number 84099xxxxx, closing the ticket until more information is provided.
You can provide the code snippet to replicate

**Comment by saisanthosh23** [comment]
Hi AfterShip/phone,
There might be a chance that the phone maybe be landline number. I’m
checking with our end customer. Thanks for the cross verification. I’ll
get back to you once I got any information

[image: photo] <https://www.dejavoosystems.com/ipos-landing/>

SaiSanthosh Saikumar
Team Lead - Portal Platform Dev, DeNovo Systems India

[image: icon] Saravana Matrix Tower LLP, 2/88 OMR, Seevaram, Perungudi,
Chennai, India 600096

[image: icon] +91 9952675129 <+919952675129>

[image: icon] ipossystems.com/

[image: linkedin]
<https://www.linkedin.com/company/ipos-systems/posts/?feedView=all&viewAsMember=true>

[image: twitter] <https://twitter.com/iPOSSystems>

[image: facebook] <https://www.facebook.com/iPOSSystemsPaymentSolutions>

[image: instagram] <https://www.instagram.com/ipossystems/?hl=en>

[image: youtube] <https://www.youtube.com/channel/UCxb4dt4xWd3ptVpeCYOmj0g>

This email transmission (including any attachments) may contain
confidential, proprietary, and/or legally privileged information, including
attorney work product. This communication is for the sole use of the
intended recipient and should be assumed to contain confidential,
proprietary, and/or legally privileged information. Any review, reliance,
or distribution by you or others, or forwarding without express permission,
is strictly prohibited. If you are not the intended recipient or have
received this email by mistake, please delete it and all copies and inform
the sender immediately.

[image: App Banner Image] <https://ipossystems.com/>

[image: __tpx__]
