### ISSUE TITLE
[Phone number format]

### ISSUE THREAD

**Issue by tamerlan-musayev** [AfterShip/phone#373]
These items must be provided:

1. +994107585572; +994997585572
3. isValid = true
4. [Reference docs/website showing that the phone number format should be valid, government websites, 3rd party websites, or even Wikipedia pages are fine.](https://ccl.kapitalbank.az/az/order/GTKR?t=kb) -> Official Azerbaijan website for getting credit, and in dropdown is list of phones

**Comment by Bossa573** [comment]
https://www.npmjs.com/package/phone/v/3.1.42 should fix this issue
