### ISSUE TITLE
Can not validate India phone number

### ISSUE THREAD

**Issue by anhcaopropine** [AfterShip/phone#376]
E.g. this is a valid India number `+912086465729` but the library detects it as invalid. Here is the code

```
var { phone } = require("phone")

console.log(phone('+912086465729'))
```

**Comment by Bossa573** [comment]
https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts#L825
<img width="453" alt="image" src="https://github.com/AfterShip/phone/assets/1013526/e059b33e-7057-4b44-9166-83314974318b">

From the current data set, India MOBILE phone numbers are:
1. 10-digit (excluding country phone code)
2. start with `6`, `7`, `8` or `9` (excluding country phone code)

Please include the documentation/websites show that the phone number starting with `2` is a valid India MOBILE phone number and reopen the ticket if needed

**Comment by anhcao142** [comment]
Hi, you're correct. After further checking, I've confirmed that the number is invalid. Sorry for wasting your time.
