### ISSUE TITLE
[feature] provide formatted number

### ISSUE THREAD

**Issue by valh1996** [AfterShip/phone#377]
Hi,

It would be great to be able to have the formatted number in the object, as this is often what I want to display to my users in the input element.

Example, user type `+18175698900`, i want to format it to `+1(817) 569-8900` to show in the input element only.

Example with `formattedPhoneNumber` property:
```ts
phone('+1(817) 569-8900', {country: ''}); 
// { isValid: true, phoneNumber: '+18175698900', formattedPhoneNumber: '+1(817) 569-890', countryIso2: 'US', countryIso3: 'USA', countryCode: '+1'}
```

**Comment by Bossa573** [comment]
Hello, thank you for the suggestion, however:

1. the goal of the lib is to provide E.164 format from any format. Formatting the phone number to other formats is out of scope.
2. In general we do not want to implement country-specific logic. The above example is for the US only. We don't have all countries data, and also there are many countries without a standard of "formatted phone number"
