### ISSUE TITLE
[Phone number format] US 728 phone code

### ISSUE THREAD

**Issue by vetribalaji** [AfterShip/phone#383]
These items must be provided:

1. What country / region - USA
2. Sample input with real phone format (Dummy phone number is fine, don't leave personal info) - 7282021234
3. Expected output - Valid +17282021234
4. Reference docs/website showing that the phone number format should be valid, government websites, 3rd party websites, or even Wikipedia pages are fine. - https://en.wikipedia.org/wiki/Area_codes_561_and_728

Important notes:
- Make sure your reported phone number is a mobile phone number - landline, VoIP, or any other phone number formats are not supported
- Creating a PR directly instead of creating an issue is much appreciated, thank you very much

**Comment by Bossa573** [comment]
https://www.npmjs.com/package/phone/v/3.1.43
Bump to 3.1.43 for supporting 728 code for US

**Comment by Bossa573** [comment]
https://github.com/AfterShip/phone/releases/tag/3.1.43

**Comment by vetribalaji** [comment]
@Bossa573 thanks!
