### ISSUE TITLE
[Phone number format]

### ISSUE THREAD

**Issue by jpBonzzay** [AfterShip/phone#384]
1. What country/region: Nicaragua
2. Sample input with real phone format: +50577485244
3. Expected output: expected to be OK, currently it returns false since it doesn't recognize a phone number starting with 7
4. Reference docs/website showing that the phone number format should be valid, government websites, 3rd party websites, or even Wikipedia pages are fine.

"Mobile phone format" at the webpage, gives the info regarding adding the prefix to the list.
[https://www.labsmobile.com/en/sms-sending-platform/nicaragua]

please add 7 to the array at mobile_begin_with
	{
		alpha2: 'NI',
		alpha3: 'NIC',
		country_code: '505',
		country_name: 'Nicaragua',
		mobile_begin_with: ['8'], <-----
		phone_number_lengths: [8]
	},

**Comment by Bossa573** [comment]
https://www.npmjs.com/package/phone/v/3.1.44
