### ISSUE TITLE
Oman country code is not supported 

### ISSUE THREAD

**Issue by anshWebelight** [AfterShip/phone#385]
**Issue related to validate Oman country number**
```
import { phone } from "phone";

const phoneDetails = phone(contactNumber);
```
In the above code, I am passing Oman country phone number like "+9687*****80 with this request I got below response for phoneDetails:
 
`{"isValid":false,"phoneNumber":null,"countryIso2":null,"countryIso3":null,"countryCode":null}`

Please check and update me on why I am getting this error from `phone()` function.

Thank you

**Comment by Bossa573** [comment]
if you consider your provided phone number is a valid *mobile* phone number, please provide any related docs show the proof.

This is the current setup for Oman *mobile* phone number (https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts#L1341)  :
phone number begin with `9`, and in total 8 digits without the country code.


Free feel to reopen the ticket if any further info provided
