### ISSUE TITLE
Invalid parsed numbers have undefined for phoneNumber

### ISSUE THREAD

**Issue by hsdonkin** [AfterShip/phone#388]
## Overview
When parsing a potentially invalid phone number, like `'555-229-3326'`, the parser will return an object with `undefined` as `phoneNumber`. This makes it hard to use strictly as a formatter and not a validator.

## Expected behavior
```
phone('555-229-3326', {country: 'US'})
=> 
{
  isValid: false
  phoneNumber: '+15032293326',
  countryIso2: 'US',
  countryIso3: 'USA',
  countryCode: '+1'
}

```

## Actual behavior
```
phone('555-229-3326', {country: 'US'})
=> 
{
  isValid: false
  phoneNumber: undefined,
  countryIso2: undefined
  countryIso3: undefined,
  countryCode: undefined
}

```

**Comment by Bossa573** [comment]
The library is not intended for the formatting only.
For formatting: 

1. Phone number
Simply remove all non [0-9] character globally.

2. Country code
If it's not a valid phone number, the module can't tell correctly which country it is and unable to pad the correct country code to the phone number.

If you're able to supply the country code i.e. you know which country, then you can exact the data from [here](https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts) and pick the corresponding country code and pad it to the phone number.
