### ISSUE TITLE
Enhance validation using external API

### ISSUE THREAD

**Issue by debopamsengupta** [AfterShip/phone#39]
https://market.mashape.com/neutrinoapi/phone-validate

This seems like an interesting API to use for validation of whether a number is mobile or not.

![image](https://cloud.githubusercontent.com/assets/9649659/13386399/03185b22-dee7-11e5-8946-5e95176c3a98.png)

vs 

![image](https://cloud.githubusercontent.com/assets/9649659/13386409/1d784dd8-dee7-11e5-8558-7cb7f97158ea.png)

@teddychan

**Comment by teddychan** [comment]
What is the payload of request?

**Comment by debopamsengupta** [comment]
Request payload:

![image](https://cloud.githubusercontent.com/assets/9649659/13387799/5f9ebb26-def5-11e5-9ea0-5f2f31765adb.png)

where `X-Mashape-Key` is generated per user per application

**Comment by debopamsengupta** [comment]
@teddychan

**Comment by teddychan** [comment]
there is same as our package.
i don't see anything relate to our node-phone lib.
