### ISSUE TITLE
WHY is this off?

### ISSUE THREAD

**Issue by Harm-Nullix** [AfterShip/phone#392]
https://github.com/AfterShip/phone/blame/43e76a99d43387892cbb7e393888584b05cd4195/lib/iso3166_data.js#L88

**Comment by Bossa573** [comment]
We don't have much background about this line (Netherlands Antilles), if you think it's incorrect, please create a PR with **the docs showing the corresponding mobile phone format**, thank you very much

**Comment by Harm-Nullix** [comment]
Even better:
https://en.wikipedia.org/wiki/Telephone_numbers_in_Cura%C3%A7ao_and_the_Caribbean_Netherlands
