### ISSUE TITLE
[phone number format] 

### ISSUE THREAD

**Issue by ArbenMehmetiPabau** [AfterShip/phone#401]
### Country/Region

indonesia

### Sample input with real phone format

+628119604561

### Reference docs/website

https://en.wikipedia.org/wiki/Telephone_numbers_in_Indonesia
Mobile phone numbers have a total of 10 to 12 digits for postpaid depending on the operator 
and this number is showing as invalid 

### Mobile phone number

- [X] I confirmed that the provided sample is a mobile phone number.

**Comment by Bossa573** [comment]
The provided sample `+628119604561` is indeed a valid mobile phone number that is recognized by the library as Indonesia, even with the testing page (you can run locally with `yarn dev`):

<img width="1236" alt="image" src="https://github.com/user-attachments/assets/90806d55-2a80-415b-bd61-2a58a0ccb8da">

closing the ticket.

**Comment by Bossa573** [comment]
<img width="624" alt="image" src="https://github.com/user-attachments/assets/5c6207e3-0eff-4426-9c8c-5215193d99b3">

this is also valid.

<img width="380" alt="image" src="https://github.com/user-attachments/assets/912cefb5-2577-4ec8-b6e2-9b6e1be3fc5b">
this is the rule for indonesia.
https://github.com/AfterShip/phone/blob/master/src/data/country_phone_data.ts#L821
"starting with 8, and with the length 9 to 12 digits"

therefore no matter 8119604561 or 811960456, it would be valid anyway
please try it locally with `yarn dev`
