### ISSUE TITLE
format issue cub

### ISSUE THREAD

**Issue by Bouzas1402** [AfterShip/phone#403]
### Country/Region

CUB

### Sample input with real phone format

+5363955533

### Reference docs/website

https://www.dimecuba.com/revista/noticias-cuba/nueva-numeracion-celulares-cuba/#:~:text=Mientras%20que%2C%20los%20que%20inician,el%20n%C3%BAmero%20asignado%20al%20SIM

### Mobile phone number

- [X] I confirmed that the provided sample is a mobile phone number.

**Comment by Bossa573** [comment]
Unable to access the provided URL,
closing the issue until further info provided.

<img width="1310" alt="image" src="https://github.com/user-attachments/assets/1bdc284f-ed19-497f-8af3-bc5c2024a53a">

**Comment by Bouzas1402** [comment]
![Captura desde 2024-10-23 10-28-35](https://github.com/user-attachments/assets/fe42c5e3-a3bf-48b3-8469-525cc90439b2)
![Captura desde 2024-10-23 10-28-16](https://github.com/user-attachments/assets/66ee3d96-c17b-463b-9609-64d8f7ec0c08)

https://www.ciegodeavila.gob.cu/es/sector-empresarial-menu-derecho-nuestra-region/division-territorial-de-etecsa-ciego-de-avila/informaciones-etecsa/7705-se-incorpora-nueva-numeracion-al-servicio-de-la-telefonia-movil-en-cuba

i add some images in case it helps, since one is from a gob page, and the last one is from a magazine. tell me if they are ok to you, thanks.

**Comment by Bossa573** [comment]
Released version 3.1.52 for adding phone number prefix '6' for cuba mobile phone number.
