### ISSUE TITLE
format issue OMN

### ISSUE THREAD

**Issue by Bouzas1402** [AfterShip/phone#404]
### Country/Region

OMN

### Sample input with real phone format

+968 2457 4334

### Reference docs/website

https://www.itu.int/itudoc/itu-t/number/omn/85604_ww9-es.doc

### Mobile phone number

- [X] I confirmed that the provided sample is a mobile phone number.

**Comment by Bossa573** [comment]
from the docs, it does not state that the phone numbers start with `2` is a mobile phone number

**Comment by Bouzas1402** [comment]
sorry, you are right. thanks.
