### ISSUE TITLE
[phone number format] Not all finnish phone number formats are covered

### ISSUE THREAD

**Issue by aojarv** [AfterShip/phone#411]
### Country/Region

FIN

### Sample input with real phone format

+358500000, +3585000000

#### There are a few thousand "short numbers" issued in Finland in the 1990's and early 2000's that are still valid and not covered by this package.
Formats: 050 XXXX and 050 XXXXX (international formats +35850XXXX and +35850XXXXX)
NSN length: 6-7 (According to Wikipedia NSN length of a finnish phone number can be anything from 5 to 12)

Reference: https://en.wikipedia.org/wiki/Telephone_numbers_in_Finland (especially the "Short numbers" section)

### Mobile phone number

- [X] I confirmed that the provided sample is a mobile phone number.

**Comment by Bossa573** [comment]
While supporting such an old and low-usage phone number format is debatable, tentatively it was added to the package until unwanted behavior found
