### ISSUE TITLE
EL SALVADOR mobile 

### ISSUE THREAD

**Issue by jpBonzzay** [AfterShip/phone#412]
### Country/Region

SLV

### Sample input with real phone format

503 602 555 55

### Reference docs/website

currently we have this: 
{
		alpha2: 'SV',
		alpha3: 'SLV',
		country_code: '503',
		country_name: 'El Salvador',
		mobile_begin_with: ['7'],
		phone_number_lengths: [8]
},
mobile numbers also can start with '6'
docs: https://en.wikipedia.org/wiki/Telephone_numbers_in_El_Salvador

### Mobile phone number

- [X] I confirmed that the provided sample is a mobile phone number.

**Comment by Bossa573** [comment]
Thank you for the reported and would be included in 3.1.54
