### ISSUE TITLE
+86 21 5206 6273 is a valid number

### ISSUE THREAD

**Issue by bkawk** [AfterShip/phone#51]
I live in China and I can dial this number +86 21 5206 6273 but when I pass in either of the below I get  undefined returned. 

+86 21 5206 6273  
+86 021 5206 6273

**Comment by teddychan** [comment]
Notice that this `phone` lib, is use to identified if the phone number is `mobile` or not.

For my understanding, all china mobile phone number exclude `+86`, must begin with `1`
