### ISSUE TITLE
Library does not detect valid mobile number in Thailand

### ISSUE THREAD

**Issue by erikhazzard** [AfterShip/phone#60]
The valid phone number being used by an iphon right now in Thailand is `+66618166864`, however, it coming up as an invalid number. It does not begin with an 8 or 9, however, it is a valid mobile phone number provided by dtac 

Relevant: https://github.com/AfterShip/phone/blob/fecd687a1345e36777aa4ffd08eee811fd3ff73e/lib/index.js#L1651

Thanks for the great library!

**Comment by teddychan** [comment]
will update the code

http://help.mobiletopup.com/knowledge-base/what-is-the-format-of-a-thai-mobile-number/
