### ISSUE TITLE
is there any option to just include the country I need (U.S) and exclude all others? 

### ISSUE THREAD

**Issue by jasan-s** [AfterShip/phone#62]
The size of lib ~44kb seems large , i was hoping if there is an option to only include U.S logic to reduce lib size.

**Comment by teddychan** [comment]
i can put this to the features or v2.0
but we use it for all countries, so won't able to do it in 1.x branch

**Comment by Bossa573** [comment]
@MauriceArikoglu Apologies, but this feature is not on our current roadmap. We can consider exploring it in the future.
