### ISSUE TITLE
Valid phone number (USA/Canada) not working

### ISSUE THREAD

**Issue by mattgrande** [AfterShip/phone#63]
Input value: `905-555-1234`

Output value: `[]`

Expected: `[ '+19055431234', 'USA' ]`

If I have time, I'll try and look into your code and issue a PR, but it probably won't be anytime soon.

**Edit:** 905 is a Canadian area code, but the formatting is the same...

**Comment by teddychan** [comment]
I just run the test.
I think the expect result should be like this:

```
phone('+1905-555-1234', '')
[ '+19055551234', 'CAN' ]

```

As `905` is a CAN prefix, not USA.
if you didn't provide `+1`, as the country prefix, it will treat it as USA, and 905 is NOT USA, so it give you empty.

May be we should do one more improvement, if USA is not match, we should try USA

**Comment by typpo** [comment]
Also experiencing this with area code 819.  This library behaves incorrectly with Canadian phone numbers that have country code 1.

**Comment by joaoritter** [comment]
Can you make CAN and USA be treated the same, regardless of the +1? It doesnt make sense for canadian users to have to type +1, but not US users. Thanks!

**Comment by danawoodman** [comment]
Same issue:

```js
phone("866-454-8855") // []
phone("+1-866-454-8855") // []
```

**Comment by Bossa573** [comment]
version 2.3.11 resolved this issue by adding CAN as default country together with USA, thanks for the information
