### ISSUE TITLE
Potential issue with +

### ISSUE THREAD

**Issue by hikkyu** [AfterShip/phone#69]
I there!

If you put: 643123123 & FR
It output: ["+33643123123", "FRA"] All right!

But if you try this combinaison: +643123123 & FR
It output : ["+643123123", "FRA"], that is not the same number (or wrong number, I don't know).

Did i missed something ?

**Comment by adamliuxy** [comment]
If you provide the 2nd parameter (country), no need to add the `+` sign for the phone number.
```
```

**Comment by HiuKwok** [comment]
Hi @adamliuxy ,
Does it mean once the plus sign is provided then the program itself would look for a country code prefix? 
Let say by typing a HKG mobile ("+852 9122 5454", "HKG") would consider to be valid cuz plus sign is provided then it look for (852) and decide it's HKG cell phone number. But on the other case when user type ("+ 9122 5454", "HKG") it would consider to be invalid cuz country number (852) prefix is not provided? 

And base on this should fill the number prefix on output if the country short form is provided?
Old case:  ("+ 9122 5454", "HKG") -> Invalid
New case:  ("+ 9122 5454", "HKG") -> Oh prefix (852) is absent but "HKG" is on -> Return ("+852 91225454, "HKG") for output?

**Comment by Bossa573** [comment]
@HiuKwok If a phone number is prefixed with a plus sign, it should be considered as there should be a country code provided i.e. for +91225454, the library should try to look up the country code `9`, `91` and so on, and eventually no result could be found.

The country iso3 parameter provides extra information for formatting the phone number, but if the library adds the country code prefix according to the country iso3, ignoring the `+` sign, it is distorting the meaning of "the digits come after the plus sign", which supposedly should be followed by country code.

And for @hikkyu cases, please do not add the `+` sign before the phone number if you are not sure the digit followed by the `+` sign is the country code.

Thanks for the information and contribution, please reopen the ticket if needed
