### ISSUE TITLE
Wrong valdiation of string?

### ISSUE THREAD

**Issue by tvld** [AfterShip/phone#70]
In my install it seems that a phone number with something like `hallo.key` validates ok... ?

**Comment by adamliuxy** [comment]
Hi, can you provide the sample code?

**Comment by tvld** [comment]
Hi... I am using this.
```js
const getPhone = require('phone') 
function parsePhone (phone) {return  getPhone(phone)[0] }       // getPhone() gives ['+18175698900', 'USA']
function isValidPhone (phone) { return parsePhone(phone)[0].length > 6  }
let valid = isValidPhone('+31654123456')  // true
let valid = isValidPhone('+hallo.key')  // true
```
I suppose my isValid code is not valid?

**Comment by adamliuxy** [comment]
When I run your code, I got this error, 
```
function isValidPhone (phone) { return parsePhone(phone).length > 6  }
                                                        ^
TypeError: Cannot read property 'length' of undefined
```
The code I executed (package version 1.0.9):
```js
'use strict';
const getPhone = require('phone') 
function parsePhone (phone) {return  getPhone(phone)[0] }       // getPhone() gives ['+18175698900', 'USA']
function isValidPhone (phone) { return parsePhone(phone).length > 6  }
//let valid = isValidPhone('+31654123456')  // true
let valid = isValidPhone('hallo.key')  
```
 The reason maybe: ```getPhone('hallo.key')``` will return empty array, and you try to get the first element from an empty array, so parsePhone(phone) will return ```undefined```.

Please check your code.

**Comment by tvld** [comment]
Sorry, I rewrote it to make it more clear as the original is part of a larger method. Now updated above...  I suppose it will work for you now? Maybe it was indeed some error of myself ...
Do I **validate** the number correctly now ?

(and thank you for your great fast response :) )

**Comment by adamliuxy** [comment]
Actually, this package doesn't validate if the number is mobile or not. It's used to normalize the mobile phone number into a E.164 format. You can read the README.md for more information.

**Comment by tvld** [comment]
I understand. But you think it is bad practice to consider it validated if parsing returned a non-empty array?

**Comment by adamliuxy** [comment]
For the existing code, I think it's bad practice. Especially, for this part ``` parsePhone(phone).length > 6 ```, you should ensure ```parsePhone(phone)``` have the property ```.length```, otherwise the code will throw error.

**Comment by tvld** [comment]
ok. thanks.. validation is crucial and your code helped :)
