### ISSUE TITLE
Undocumented feature

### ISSUE THREAD

**Issue by dekelev** [AfterShip/phone#76]
Seems that forcing the first character of the phone argument to be a '+' sign will disable the default country feature. I do need this feature disabled, but I haven't seen any note about this behavior in the documentation.

Example:

**847-555-5555** results in prefixed number with USA country code
**+847-555-5555** fails validation and results in []

**Comment by Bossa573** [comment]
if you add the "plus" sign, it means that the phone number should include the country code,
if the phone number does not have country code, please remove the "plus" sign and let the module to parse
