### ISSUE TITLE
Toll Free returning blank results

### ISSUE THREAD

**Issue by TimMeade** [AfterShip/phone#81]
It appears USA toll free returns blanks.   I'm not sure if this is the desired return or not, but we certainly need those straightened out also.

**Comment by brainthinks** [comment]
same here.  I haven't yet tested with `2.0.0-rc.1`, but 800 numbers don't appear to be identified as valid.

**Comment by brainthinks** [comment]
I went through the source code - it appears that the `mobile_begin_with` property for the USA entry in the `lib/iso3166_data.js` is every area code that this library supports - it is not a mobile specific thing, at least from what I can tell.  Can I simply add "800", and perhaps "900", to that array?  If you're ok with this, I'll create a merge request.

**Comment by Bossa573** [comment]
this library intends to support mobile phone number `only`, therefore supposedly toll-free number is not supported
