### ISSUE TITLE
Is it possible to give a number and a MCC instead of the country letters?

### ISSUE THREAD

**Issue by Natim** [AfterShip/phone#9]
Would it be possible to get the MCC instead of the country letters?
It could be good to document the country code list as well.

Here is the table I am using: https://mxr.mozilla.org/gaia/source/shared/resources/mcc.json

**Comment by abhishiv** [comment]
I think this would be great as well. Specially because I imagine in a lot of cases you have the numerical code rather than country abbreviation.

**Comment by Bossa573** [comment]
MCC lookup should not be the purpose of this library, will close this issue
