### ISSUE TITLE
Wrong validation for Panama

### ISSUE THREAD

**Issue by christopher-acceptto** [AfterShip/phone#92]
Phone numbers in Panama are either 7 or 8 digits long and Mobile prefix is 6 only.

[https://en.wikipedia.org/wiki/Telephone_numbers_in_Panama](url)

**Comment by HiuKwok** [comment]
@christopher-acceptto Hi there, yes you are right about the mobile prefix. The mobile number on Panama is always start from 6, however according to my knowledge only landline would have 7 digits but not the for mobile. It's always in 8 digits.
![image](https://user-images.githubusercontent.com/37996731/44299468-f341df80-a328-11e8-9a0e-2fc440646fc5.png)

Which I try to double check with the site that @teddychan posted. 
![image](https://user-images.githubusercontent.com/37996731/44299479-2edca980-a329-11e8-8628-9789c998889f.png)

Hence I reckon by removing '5' from below would fix the issue
https://github.com/AfterShip/phone/blob/9cb22e83d15f115262a36c0155b242ec0b4d0465/lib/iso3166Data.js#L1330

**Comment by HiuKwok** [comment]
For everyone who interest in this issue, fix is up on: https://github.com/AfterShip/phone/pull/112

**Comment by Bossa573** [comment]
Should be merged and published already
