### ISSUE TITLE
Unsupported countries (commented out)

### ISSUE THREAD

**Issue by ctessier** [AfterShip/phone#95]
Hi,

Some countries are commented out and therefore unsupported. Why is so please?

Example with British Indican Ocean Territory : https://github.com/AfterShip/phone/blob/master/lib/iso3166_data.js#L791

Thank you

**Comment by dawnmessier** [comment]
When will these be uncommented? My feature does not work without these countries

**Comment by teddychan** [comment]
Notice this library is used to detect the mobile phone format.
We have no way to verify the mobile phone format, or there is no way to send SMS to those countries.
thus, it is commented out first.

If you can help to provide the mobile phone format for those countries, we are happy to merge the PR.

**Comment by Bossa573** [comment]
At the moment there are no data (no `mobile_begin_with` or even no `country_code`) under those countries which have been commented out,
please create separate issues or PR to discuss, 
will close this issue for now, thanks
