### ISSUE TITLE
New numbers in China.

### ISSUE THREAD

**Issue by xream** [AfterShip/phone#96]
Ministry of Industry and Information Technology of China disclosed a number of new numbers in 2017 tenth "telecommunications network code resource use certificate"

China Telecom: 199
China Mobile: 198
China Unicom: 166

**Comment by HiuKwok** [comment]
Hi there @xream,
From what understand the current logic for validating mobile number for China is kind of loosen. 
It only check for the first two digit.
https://github.com/AfterShip/phone/blob/0546c98636c0740e80b3b04a4e4a74698c0fc472/lib/iso3166Data.js#L350-L355

Hence it should work just fine. For those numbers which are 199, 198, 166 respectively. But anyway extra test case is needed for against those new pattern would be great to avoid confusion I think.

**Comment by Bossa573** [comment]
PR is merged for the extra test cases, 
please reopen this issue if needed, thanks for the contribution
